### ISSUE TITLE
Outage tasks for 2022-11-10

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#798]
- [x] Run noctua-models-migration pipeline for @vanaukenk (day before? morning of?) to get report
- [x] ~~Merge in https://github.com/geneontology/minerva/pull/505~~ Tests not passing
- [x] Refresh minerva code with latest from minerva `master`
- [x] Merge reactome updates https://github.com/geneontology/noctua-models/pull/247
- [x] Fix models with incorrect reactome schema: https://github.com/geneontology/go-site/issues/1924
- [x] Run `replaced_by` term update on blazegraph (@vanaukenk)
- [x] Cycle minerva to get latest ontology
- [x] Cycle barista to get latest groups.yaml (update groups.yaml too) https://github.com/geneontology/go-site/issues/1924 
- [x] ~~Update NEO~~ canceled due to apparent timeout failure; machine too busy? Not too bad as we updated out of sync last week 
- [x] Prep ticket for next outage: https://github.com/geneontology/noctua/issues/803

**Comment by dustine32** [comment]
PR to come later today: apply https://github.com/geneontology/reactome-go-cams/pull/9 to `noctua-models/master` (drop-n-reload of Reactome models). @kltm Would this be OK for Thursday?

**Comment by ukemi** [comment]
Thanks @dustine32 !!!!

**Comment by dustine32** [comment]
Reactome models PR is in! https://github.com/geneontology/noctua-models/pull/247

**Comment by dustine32** [comment]
@ukemi No prob, and thank you for nudging me - I meant to get this in place last week!

**Comment by kltm** [comment]
@dustine32 I have no problem with this and am adding it to the list, but will leave overriding either way to @vanaukenk .

**Comment by ukemi** [comment]
@suzialeksander. The models are currently loaded into dev if you need a spot-check comparison. They all have Reactome in the title. For some reason there are still issues searching by group. Hopefully we can track that down by the next load.

**Comment by dustine32** [comment]
@ukemi I think I just figured out the group thing and explained it further in https://github.com/geneontology/noctua-models/pull/247#issuecomment-1307747993.

**Comment by kltm** [comment]
@suzialeksander Diff ready: http://skyhook.berkeleybop.org/noctua-models-migrations/reports/ontology-replaced-by.diff
